// Code generated by "stringer -type=ConnectionPriority"; DO NOT EDIT.

package cm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ConnectionPriorityLow-0]
	_ = x[ConnectionPriorityHigh-1]
	_ = x[ConnectionPriorityScheduled-2]
	_ = x[ConnectionPriorityUrgent-3]
}

const _ConnectionPriority_name = "ConnectionPriorityLowConnectionPriorityHighConnectionPriorityScheduledConnectionPriorityUrgent"

var _ConnectionPriority_index = [...]uint8{0, 21, 43, 70, 94}

func (i ConnectionPriority) String() string {
	if i >= ConnectionPriority(len(_ConnectionPriority_index)-1) {
		return "ConnectionPriority(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ConnectionPriority_name[_ConnectionPriority_index[i]:_ConnectionPriority_index[i+1]]
}
