// Code generated by "stringer -type=ConnectionType"; DO NOT EDIT.

package cm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ConnectionTypeNull-0]
	_ = x[ConnectionTypeMulticast-1]
	_ = x[ConnectionTypePointToPoint-2]
	_ = x[ConnectionTypeReserved-3]
}

const _ConnectionType_name = "ConnectionTypeNullConnectionTypeMulticastConnectionTypePointToPointConnectionTypeReserved"

var _ConnectionType_index = [...]uint8{0, 18, 41, 67, 89}

func (i ConnectionType) String() string {
	if i >= ConnectionType(len(_ConnectionType_index)-1) {
		return "ConnectionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ConnectionType_name[_ConnectionType_index[i]:_ConnectionType_index[i+1]]
}
