// Code generated by "stringer -type=GeneralStatus"; DO NOT EDIT.

package cip

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusSuccess-0]
	_ = x[StatusCommunicationProblem-1]
	_ = x[StatusResourceUnavailable-2]
	_ = x[StatusInvalidParameterValue-3]
	_ = x[StatusPathSegmentError-4]
	_ = x[StatusPathDestinationUnknown-5]
	_ = x[StatusPartialTransfer-6]
	_ = x[StatusConnectionLost-7]
	_ = x[StatusServiceNotSupported-8]
	_ = x[StatusInvalidAttributeValue-9]
	_ = x[StatusAttributeListError-10]
	_ = x[StatusAlreadyInRequestedMode-11]
	_ = x[StatusObjectStateConflict-12]
	_ = x[StatusObjectAlreadyExists-13]
	_ = x[StatusAttributeNotSetable-14]
	_ = x[StatusPriveledgeViolation-15]
	_ = x[StatusDeviceStateConflict-16]
	_ = x[StatusReplyDataTooLarge-17]
	_ = x[StatusFragmentationOfPrimitiveValue-18]
	_ = x[StatusNotEnoughData-19]
	_ = x[StatusAttributeNotSupported-20]
	_ = x[StatusTooMuchData-21]
	_ = x[StatusObjectInstanceDoesNotExist-22]
	_ = x[StatusFragmentationOutOfSequence-23]
	_ = x[StatusNoStoredAttributeData-24]
	_ = x[StatusStoreOperationFailure-25]
	_ = x[StatusRoutingFailureReqPacketTooLarge-26]
	_ = x[StatusRoutingFailureResPacketTooLarge-27]
	_ = x[StatusMissingAttributeListData-28]
	_ = x[StatusInvalidAttributeList-29]
	_ = x[StatusEmbeddedServiceError-30]
	_ = x[StatusVendorSpecificError-31]
	_ = x[StatusInvalidParameter-32]
	_ = x[StatusWriteOnlyOnceValueAlreadyWritten-33]
	_ = x[StatusInvalidReply-34]
	_ = x[StatusBufferOverflow-35]
	_ = x[StatusMessageFormatError-36]
	_ = x[StatusKeyFailureInPath-37]
	_ = x[StatusPathSizeInvalid-38]
	_ = x[StatusUnexpectedAttributeInList-39]
	_ = x[StatusInvalidMemeberID-40]
	_ = x[StatusMemberNotSettable-41]
	_ = x[StatusGroup2OnlyServerGeneralFailure-42]
	_ = x[StatusUknownModbusError-43]
	_ = x[StatusAttributeNotGettable-44]
	_ = x[StatusInstanceNotDeletable-45]
}

const _GeneralStatus_name = "StatusSuccessStatusCommunicationProblemStatusResourceUnavailableStatusInvalidParameterValueStatusPathSegmentErrorStatusPathDestinationUnknownStatusPartialTransferStatusConnectionLostStatusServiceNotSupportedStatusInvalidAttributeValueStatusAttributeListErrorStatusAlreadyInRequestedModeStatusObjectStateConflictStatusObjectAlreadyExistsStatusAttributeNotSetableStatusPriveledgeViolationStatusDeviceStateConflictStatusReplyDataTooLargeStatusFragmentationOfPrimitiveValueStatusNotEnoughDataStatusAttributeNotSupportedStatusTooMuchDataStatusObjectInstanceDoesNotExistStatusFragmentationOutOfSequenceStatusNoStoredAttributeDataStatusStoreOperationFailureStatusRoutingFailureReqPacketTooLargeStatusRoutingFailureResPacketTooLargeStatusMissingAttributeListDataStatusInvalidAttributeListStatusEmbeddedServiceErrorStatusVendorSpecificErrorStatusInvalidParameterStatusWriteOnlyOnceValueAlreadyWrittenStatusInvalidReplyStatusBufferOverflowStatusMessageFormatErrorStatusKeyFailureInPathStatusPathSizeInvalidStatusUnexpectedAttributeInListStatusInvalidMemeberIDStatusMemberNotSettableStatusGroup2OnlyServerGeneralFailureStatusUknownModbusErrorStatusAttributeNotGettableStatusInstanceNotDeletable"

var _GeneralStatus_index = [...]uint16{0, 13, 39, 64, 91, 113, 141, 162, 182, 207, 234, 258, 286, 311, 336, 361, 386, 411, 434, 469, 488, 515, 532, 564, 596, 623, 650, 687, 724, 754, 780, 806, 831, 853, 891, 909, 929, 953, 975, 996, 1027, 1049, 1072, 1108, 1131, 1157, 1183}

func (i GeneralStatus) String() string {
	if i >= GeneralStatus(len(_GeneralStatus_index)-1) {
		return "GeneralStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GeneralStatus_name[_GeneralStatus_index[i]:_GeneralStatus_index[i+1]]
}
