// Code generated by "stringer -type=ServiceCode"; DO NOT EDIT.

package cip

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GetAttributesAll-1]
	_ = x[SetAttributesAll-2]
	_ = x[GetAttributeList-3]
	_ = x[SetAttributeList-4]
	_ = x[Reset-5]
	_ = x[Start-6]
	_ = x[Stop-7]
	_ = x[Create-8]
	_ = x[Delete-9]
	_ = x[MultipleServicePacket-10]
	_ = x[ApplyAttributes-13]
	_ = x[GetAttributeSingle-14]
	_ = x[SetAttributeSingle-16]
	_ = x[FindNextObjectInstance-17]
	_ = x[Restore-21]
	_ = x[Save-22]
	_ = x[NoOP-23]
	_ = x[GetMember-24]
	_ = x[SetMember-25]
	_ = x[InsertMember-26]
	_ = x[RemoveMember-27]
	_ = x[GroupSync-28]
	_ = x[GetConnectionPointMemberList-29]
	_ = x[ForwardClose-78]
	_ = x[UnconnectedSend-82]
	_ = x[ForwardOpen-84]
	_ = x[GetConnectionData-86]
	_ = x[SearchConnectionData-87]
	_ = x[GetConnectionOwner-90]
	_ = x[LargeForwardOpen-91]
	_ = x[GetAttributesAllResponse-129]
	_ = x[SetAttributesAllResponse-130]
	_ = x[GetAttributeListResponse-131]
	_ = x[SetAttributeListResponse-132]
	_ = x[ResetResponse-133]
	_ = x[StartResponse-134]
	_ = x[StopResponse-135]
	_ = x[CreateResponse-136]
	_ = x[DeleteResponse-137]
	_ = x[MultipleServicePacketResponse-138]
	_ = x[ApplyAttributesResponse-141]
	_ = x[GetAttributeSingleResponse-142]
	_ = x[SetAttributeSingleResponse-144]
	_ = x[FindNextObjectInstanceResponse-145]
	_ = x[RestoreResponse-149]
	_ = x[SaveResponse-150]
	_ = x[NoOPResponse-151]
	_ = x[GetMemberResponse-152]
	_ = x[SetMemberResponse-153]
	_ = x[InsertMemberResponse-154]
	_ = x[RemoveMemberResponse-155]
	_ = x[GroupSyncResponse-156]
	_ = x[GetConnectionPointMemberListResponse-157]
	_ = x[ForwardCloseResponse-206]
	_ = x[UnconnectedSendResponse-210]
	_ = x[ForwardOpenResponse-212]
	_ = x[GetConnectionDataResponse-214]
	_ = x[SearchConnectionDataResponse-215]
	_ = x[GetConnectionOwnerResponse-218]
	_ = x[LargeForwardOpenResponse-219]
}

const _ServiceCode_name = "GetAttributesAllSetAttributesAllGetAttributeListSetAttributeListResetStartStopCreateDeleteMultipleServicePacketApplyAttributesGetAttributeSingleSetAttributeSingleFindNextObjectInstanceRestoreSaveNoOPGetMemberSetMemberInsertMemberRemoveMemberGroupSyncGetConnectionPointMemberListForwardCloseUnconnectedSendForwardOpenGetConnectionDataSearchConnectionDataGetConnectionOwnerLargeForwardOpenGetAttributesAllResponseSetAttributesAllResponseGetAttributeListResponseSetAttributeListResponseResetResponseStartResponseStopResponseCreateResponseDeleteResponseMultipleServicePacketResponseApplyAttributesResponseGetAttributeSingleResponseSetAttributeSingleResponseFindNextObjectInstanceResponseRestoreResponseSaveResponseNoOPResponseGetMemberResponseSetMemberResponseInsertMemberResponseRemoveMemberResponseGroupSyncResponseGetConnectionPointMemberListResponseForwardCloseResponseUnconnectedSendResponseForwardOpenResponseGetConnectionDataResponseSearchConnectionDataResponseGetConnectionOwnerResponseLargeForwardOpenResponse"

var _ServiceCode_map = map[ServiceCode]string{
	1:   _ServiceCode_name[0:16],
	2:   _ServiceCode_name[16:32],
	3:   _ServiceCode_name[32:48],
	4:   _ServiceCode_name[48:64],
	5:   _ServiceCode_name[64:69],
	6:   _ServiceCode_name[69:74],
	7:   _ServiceCode_name[74:78],
	8:   _ServiceCode_name[78:84],
	9:   _ServiceCode_name[84:90],
	10:  _ServiceCode_name[90:111],
	13:  _ServiceCode_name[111:126],
	14:  _ServiceCode_name[126:144],
	16:  _ServiceCode_name[144:162],
	17:  _ServiceCode_name[162:184],
	21:  _ServiceCode_name[184:191],
	22:  _ServiceCode_name[191:195],
	23:  _ServiceCode_name[195:199],
	24:  _ServiceCode_name[199:208],
	25:  _ServiceCode_name[208:217],
	26:  _ServiceCode_name[217:229],
	27:  _ServiceCode_name[229:241],
	28:  _ServiceCode_name[241:250],
	29:  _ServiceCode_name[250:278],
	78:  _ServiceCode_name[278:290],
	82:  _ServiceCode_name[290:305],
	84:  _ServiceCode_name[305:316],
	86:  _ServiceCode_name[316:333],
	87:  _ServiceCode_name[333:353],
	90:  _ServiceCode_name[353:371],
	91:  _ServiceCode_name[371:387],
	129: _ServiceCode_name[387:411],
	130: _ServiceCode_name[411:435],
	131: _ServiceCode_name[435:459],
	132: _ServiceCode_name[459:483],
	133: _ServiceCode_name[483:496],
	134: _ServiceCode_name[496:509],
	135: _ServiceCode_name[509:521],
	136: _ServiceCode_name[521:535],
	137: _ServiceCode_name[535:549],
	138: _ServiceCode_name[549:578],
	141: _ServiceCode_name[578:601],
	142: _ServiceCode_name[601:627],
	144: _ServiceCode_name[627:653],
	145: _ServiceCode_name[653:683],
	149: _ServiceCode_name[683:698],
	150: _ServiceCode_name[698:710],
	151: _ServiceCode_name[710:722],
	152: _ServiceCode_name[722:739],
	153: _ServiceCode_name[739:756],
	154: _ServiceCode_name[756:776],
	155: _ServiceCode_name[776:796],
	156: _ServiceCode_name[796:813],
	157: _ServiceCode_name[813:849],
	206: _ServiceCode_name[849:869],
	210: _ServiceCode_name[869:892],
	212: _ServiceCode_name[892:911],
	214: _ServiceCode_name[911:936],
	215: _ServiceCode_name[936:964],
	218: _ServiceCode_name[964:990],
	219: _ServiceCode_name[990:1014],
}

func (i ServiceCode) String() string {
	if str, ok := _ServiceCode_map[i]; ok {
		return str
	}
	return "ServiceCode(" + strconv.FormatInt(int64(i), 10) + ")"
}
