// Code generated by "stringer -type=ConnectionPointType"; DO NOT EDIT.

package adapter

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ListenOnly-1]
	_ = x[InputOnly-2]
	_ = x[ExclusiveOwner-4]
	_ = x[RedundantOwner-8]
}

const (
	_ConnectionPointType_name_0 = "ListenOnlyInputOnly"
	_ConnectionPointType_name_1 = "ExclusiveOwner"
	_ConnectionPointType_name_2 = "RedundantOwner"
)

var (
	_ConnectionPointType_index_0 = [...]uint8{0, 10, 19}
)

func (i ConnectionPointType) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _ConnectionPointType_name_0[_ConnectionPointType_index_0[i]:_ConnectionPointType_index_0[i+1]]
	case i == 4:
		return _ConnectionPointType_name_1
	case i == 8:
		return _ConnectionPointType_name_2
	default:
		return "ConnectionPointType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
