// Code generated by "stringer -type=RealTimeFormat"; DO NOT EDIT.

package adapter

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ModelessFormat-1]
	_ = x[ZeroLengthFormat-2]
	_ = x[HeartbeatFormat-4]
	_ = x[Header32BitFormat-8]
}

const (
	_RealTimeFormat_name_0 = "ModelessFormatZeroLengthFormat"
	_RealTimeFormat_name_1 = "HeartbeatFormat"
	_RealTimeFormat_name_2 = "Header32BitFormat"
)

var (
	_RealTimeFormat_index_0 = [...]uint8{0, 14, 30}
)

func (i RealTimeFormat) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _RealTimeFormat_name_0[_RealTimeFormat_index_0[i]:_RealTimeFormat_index_0[i+1]]
	case i == 4:
		return _RealTimeFormat_name_1
	case i == 8:
		return _RealTimeFormat_name_2
	default:
		return "RealTimeFormat(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
