package encap

/*
Either an originator or a target may send a NOP command.  No reply shall be generated by this
command.  The data portion of the command shall be from 0 to 65511 bytes long.  The receiver
shall ignore any data that is contained in the message. A NOP command does not require that a
session be established.
*/
type NOPRequest Request

type _NOPRequest Packet

func (self *Packet) ToNOPRequest() (NOPRequest, error) { return (*_NOPRequest)(self), nil }
