// Code generated by "stringer -type=Format"; DO NOT EDIT.

package epath

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Format4-4]
	_ = x[Format5-5]
}

const _Format_name = "Format4Format5"

var _Format_index = [...]uint8{0, 7, 14}

func (i Format) String() string {
	i -= 4
	if i >= Format(len(_Format_index)-1) {
		return "Format(" + strconv.FormatInt(int64(i+4), 10) + ")"
	}
	return _Format_name[_Format_index[i]:_Format_index[i+1]]
}
