// Code generated by "stringer -type=LogicalSegType"; DO NOT EDIT.

package epath

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LogicalSegTypeClassID-0]
	_ = x[LogicalSegTypeInstanceID-4]
	_ = x[LogicalSegTypeMemberID-8]
	_ = x[LogicalSegTypeConnectionPoint-12]
	_ = x[LogicalSegTypeAttributeID-16]
	_ = x[LogicalSegTypeSpecial-20]
	_ = x[LogicalSegTypeServiceID-24]
	_ = x[LogicalSegTypeExtendedLogical-28]
	_ = x[LogicalSegTypeMask-28]
}

const (
	_LogicalSegType_name_0 = "LogicalSegTypeClassID"
	_LogicalSegType_name_1 = "LogicalSegTypeInstanceID"
	_LogicalSegType_name_2 = "LogicalSegTypeMemberID"
	_LogicalSegType_name_3 = "LogicalSegTypeConnectionPoint"
	_LogicalSegType_name_4 = "LogicalSegTypeAttributeID"
	_LogicalSegType_name_5 = "LogicalSegTypeSpecial"
	_LogicalSegType_name_6 = "LogicalSegTypeServiceID"
	_LogicalSegType_name_7 = "LogicalSegTypeExtendedLogical"
)

func (i LogicalSegType) String() string {
	switch {
	case i == 0:
		return _LogicalSegType_name_0
	case i == 4:
		return _LogicalSegType_name_1
	case i == 8:
		return _LogicalSegType_name_2
	case i == 12:
		return _LogicalSegType_name_3
	case i == 16:
		return _LogicalSegType_name_4
	case i == 20:
		return _LogicalSegType_name_5
	case i == 24:
		return _LogicalSegType_name_6
	case i == 28:
		return _LogicalSegType_name_7
	default:
		return "LogicalSegType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
