// Code generated by "stringer -type=LogicalFormatServiceID"; DO NOT EDIT.

package epath

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LogicalFormatServiceID8Bit-0]
	_ = x[LogicalFormatServiceIDMask-3]
}

const (
	_LogicalFormatServiceID_name_0 = "LogicalFormatServiceID8Bit"
	_LogicalFormatServiceID_name_1 = "LogicalFormatServiceIDMask"
)

func (i LogicalFormatServiceID) String() string {
	switch {
	case i == 0:
		return _LogicalFormatServiceID_name_0
	case i == 3:
		return _LogicalFormatServiceID_name_1
	default:
		return "LogicalFormatServiceID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
