// Code generated by "stringer -type=LogicalFormat"; DO NOT EDIT.

package epath

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LogicalFormat8Bit-0]
	_ = x[LogicalFormat16Bit-1]
	_ = x[LogicalFormat32Bit-2]
	_ = x[LogicalFormatReserved-3]
	_ = x[LogicalFormatMask-3]
}

const _LogicalFormat_name = "LogicalFormat8BitLogicalFormat16BitLogicalFormat32BitLogicalFormatReserved"

var _LogicalFormat_index = [...]uint8{0, 17, 35, 53, 74}

func (i LogicalFormat) String() string {
	if i >= LogicalFormat(len(_LogicalFormat_index)-1) {
		return "LogicalFormat(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LogicalFormat_name[_LogicalFormat_index[i]:_LogicalFormat_index[i+1]]
}
